#!/bin/bash

if [ ! -f /tmp/lock_populate_xenia_nws ]; then
  touch /tmp/lock_populate_xenia_nws
  /home/xeniaprod/scripts/postgresql/feeds/federal/mk_sql_for_xenia.pl nws 24 /home/xeniaprod/tmp/sqlfiles/nws.sql debug
  psql -U xeniaprod -d xenia -f /home/xeniaprod/tmp/sqlfiles/nws.sql
  rm -f /tmp/lock_populate_xenia_nws
fi
