-- scalar data dictionary listing (standard listing)
-- select t1.row_id,t2.standard_name,t3.standard_name from m_scalar_type t1,obs_type t2,uom_type t3 where t1.obs_type_id = t2.row_id and t1.uom_type_id = t3.row_id;

INSERT INTO "obs_type" VALUES(1,'wind_speed','Wind speed');
INSERT INTO "obs_type" VALUES(2,'wind_gust','Maximum instantaneous wind speed (usually no more than but not limited to 10 seconds) within a sample averaging interval');
INSERT INTO "obs_type" VALUES(3,'wind_from_direction','Direction from which wind is blowing.  Meteorological Convention.');
INSERT INTO "obs_type" VALUES(4,'air_pressure','Pressure exerted by overlying air.');
INSERT INTO "obs_type" VALUES(5,'air_temperature','Temperature of air, in situ.');
INSERT INTO "obs_type" VALUES(6,'water_temperature','Water temperature');
INSERT INTO "obs_type" VALUES(7,'water_conductivity','Ability of a specific volume (1 cubic centimeter) of water to pass an electrical current');
INSERT INTO "obs_type" VALUES(8,'water_pressure','Water Pressure');
INSERT INTO "obs_type" VALUES(9,'water_salinity','Water Salinity');
INSERT INTO "obs_type" VALUES(10,'chl_concentration','concentration of cholorophyll-a in a defined volume of water');
INSERT INTO "obs_type" VALUES(11,'current_speed','Water Current Magnitude');
INSERT INTO "obs_type" VALUES(12,'current_to_direction','Direction toward which current is flowing');
INSERT INTO "obs_type" VALUES(13,'significant_wave_height','Significant wave height');
INSERT INTO "obs_type" VALUES(14,'dominant_wave_period','Dominant Wave period');
INSERT INTO "obs_type" VALUES(15,'significant_wave_to_direction','Significant Wave Direction');
INSERT INTO "obs_type" VALUES(18,'sea_surface_temperature','Surface Water temperature');
INSERT INTO "obs_type" VALUES(19,'sea_bottom_temperature','Bottom Water temperature');
INSERT INTO "obs_type" VALUES(20,'sea_surface_eastward_current','East/West component of ocean current near the sea surface, Eastward is positive');
INSERT INTO "obs_type" VALUES(21,'sea_surface_northward_current','North/South component of ocean current near the sea surface, Northward is positive');
INSERT INTO "obs_type" VALUES(22,'relative_humidity','Relative humidity');
INSERT INTO "obs_type" VALUES(23,'water_level','water_level');
INSERT INTO "obs_type" VALUES(24,'bottom_water_salinity','Bottom Water Salinity');
INSERT INTO "obs_type" VALUES(25,'surface_water_salinity','Surface Water Salinity');
INSERT INTO "obs_type" VALUES(26,'bottom_chlorophyll','Bottom Water Chlorophyll');
INSERT INTO "obs_type" VALUES(27,'surface_chlorophyll','Bottom Water Chlorophyll');
INSERT INTO "obs_type" VALUES(28,'salinity','salinity');
INSERT INTO "obs_type" VALUES(29,'precipitation','measured precipitation or rainfall');
INSERT INTO "obs_type" VALUES(30,'solar_radiation','measured solar radiation or sunlight');
INSERT INTO "obs_type" VALUES(31,'eastward_current','East/West component of water current, Eastward is positive');
INSERT INTO "obs_type" VALUES(32,'northward_current','North/South component of water current, Northward is positive');
INSERT INTO "obs_type" VALUES(33,'precipitation_accumulated_daily','measured precipitation or rainfall daily accumulation');
INSERT INTO "obs_type" VALUES(34,'oxygen_concentration','concentration of oxygen in a defined volume of water');
INSERT INTO "obs_type" VALUES(35,'turbidity','Measure of light scattering due to suspended material in water.');
INSERT INTO "obs_type" VALUES(36,'ph','(from potential of Hydrogen) the logarithm of the reciprocal of hydrogen-ion concentration in gram atoms per liter');
INSERT INTO "obs_type" VALUES(37,'visibility','Greatest distance an object can be seen and identified. Usually refering to visibility in air');
INSERT INTO "obs_type" VALUES(38,'precipitation_accumulated_storm','measured precipitation or rainfall storm accumulation');
INSERT INTO "obs_type" VALUES(39,'drifter_speed','drifter speed');
INSERT INTO "obs_type" VALUES(40,'drifter_direction','direction which drifter is moving in degrees from North');
INSERT INTO "obs_type" VALUES(41,'gage_height','gage_height');
INSERT INTO "obs_type" VALUES(42,'depth','approximate water depth');
INSERT INTO "obs_type" VALUES(43,'discharge','cubic volume discharge');
INSERT INTO "obs_type" VALUES(44,'stream_velocity','inland stream velocity');
INSERT INTO "obs_type" VALUES(45,'mean_wave_direction_peak_period','NDBC definition - Mean wave direction corresponding to energy of the dominant period (DPD). The units are degrees from true North just like wind direction.');
INSERT INTO "obs_type" VALUES(46,'average_wave_period','Average period (seconds) of the highest one-third of the wave observed during 1 20 minute sampling period');
INSERT INTO "obs_type" VALUES(47,'swell_height','vertical distance (meters) between any swell crest and the succeeding swell wave trough');
INSERT INTO "obs_type" VALUES(48,'swell_period','the time (usually measured in seconds) that takes successive swell wave crests or troughs pass a fixed point');
INSERT INTO "obs_type" VALUES(49,'swell_direction','the compass direction from which the swell wave are coming from');
INSERT INTO "obs_type" VALUES(50,'wind_wave_height','vertical distance (meters) between any wind wave crest and the succeeding wind wave trough');
INSERT INTO "obs_type" VALUES(51,'wind_wave_period','the time (in seconds) that it takes successive wind wave crests or troughs to pass a fixed point');
INSERT INTO "obs_type" VALUES(52,'wind_wave_direction','the compass direction (in degrees) from which the wind waves are coming');
INSERT INTO "obs_type" VALUES(53,'directional_wave_parameter','');
INSERT INTO "obs_type" VALUES(54,'principal_wave_direction','');
INSERT INTO "obs_type" VALUES(55,'spectral_energy','');
INSERT INTO "obs_type" VALUES(56,'center_frequencies','');
INSERT INTO "obs_type" VALUES(57,'swell_wave_direction','');
INSERT INTO "obs_type" VALUES(58,'bandwidths','');
INSERT INTO "obs_type" VALUES(60,'mean_wave_direction_peak_period','');
INSERT INTO "obs_type" VALUES(61,'polar_coordinate_r_1','');
INSERT INTO "obs_type" VALUES(62,'polar_coordinate_r_2','');
INSERT INTO "obs_type" VALUES(63,'fourier_coefficient_a_1','');
INSERT INTO "obs_type" VALUES(64,'fourier_coefficient_b_1','');
INSERT INTO "obs_type" VALUES(65,'fourier_coefficient_a_2','');
INSERT INTO "obs_type" VALUES(66,'fourier_coefficient_b_2','');
INSERT INTO "obs_type" VALUES(67,'check_factor','');

INSERT INTO "uom_type" VALUES(1,'m_s-1','meters per second','m/s');
INSERT INTO "uom_type" VALUES(2,'degrees_true','degrees clockwise from true north','deg');
INSERT INTO "uom_type" VALUES(3,'celsius','degrees celsius','deg C');
INSERT INTO "uom_type" VALUES(4,'mb','1 mb = 0.001 bar = 100 Pa = 1 000 dyn/cm^2','mb');
INSERT INTO "uom_type" VALUES(5,'mS_cm-1','milliSiemens per centimeter','mS/cm');
INSERT INTO "uom_type" VALUES(6,'m','meter','m');
INSERT INTO "uom_type" VALUES(7,'s','seconds','s');
INSERT INTO "uom_type" VALUES(8,'cm_s-1','centrimeter per second','cm/s');
INSERT INTO "uom_type" VALUES(9,'millibar','millibar','mb');
INSERT INTO "uom_type" VALUES(10,'psu','practical salinity units','psu');
INSERT INTO "uom_type" VALUES(11,'percent','percentage','%');
INSERT INTO "uom_type" VALUES(12,'ppt','parts per thousand','ppt');
INSERT INTO "uom_type" VALUES(13,'ug_L-1','micrograms per liter','ug/L');
INSERT INTO "uom_type" VALUES(14,'millimeter','millimeter','mm');
INSERT INTO "uom_type" VALUES(15,'millimoles_per_m^2','millimoles per meter squared','millimoles per m^2');
INSERT INTO "uom_type" VALUES(16,'units','a dimensionless unit','units');
INSERT INTO "uom_type" VALUES(17,'ntu','nephelometric turbidity units','ntu');
INSERT INTO "uom_type" VALUES(18,'mg_L-1','milligrams per liter','mg/L');
INSERT INTO "uom_type" VALUES(19,'nautical_miles','equal to 1.151 statue miles','nautical miles');
INSERT INTO "uom_type" VALUES(20,'mph','miles per hour','mph');
INSERT INTO "uom_type" VALUES(21,'knots','knots','knots');
INSERT INTO "uom_type" VALUES(22,'ft','feet','ft');
INSERT INTO "uom_type" VALUES(23,'cubic_ft_s-1','cubic feet per second','ft^3/s');
INSERT INTO "uom_type" VALUES(24,'ft_s-1','feet per second','ft/s');
INSERT INTO "uom_type" VALUES(25,'m^2_Hz-1','square meter per hz','m**2/Hz');
INSERT INTO "uom_type" VALUES(26,'Hz','Hz','Hz');
INSERT INTO "uom_type" VALUES(27,'undefined','undefined','undefined');

INSERT INTO "m_scalar_type" VALUES(1,1,1);
INSERT INTO "m_scalar_type" VALUES(2,2,1);
INSERT INTO "m_scalar_type" VALUES(3,3,2);
INSERT INTO "m_scalar_type" VALUES(4,4,4);
INSERT INTO "m_scalar_type" VALUES(5,5,3);
INSERT INTO "m_scalar_type" VALUES(6,6,3);
INSERT INTO "m_scalar_type" VALUES(7,7,5);
INSERT INTO "m_scalar_type" VALUES(8,8,4);
INSERT INTO "m_scalar_type" VALUES(9,9,10);
INSERT INTO "m_scalar_type" VALUES(10,10,13);
INSERT INTO "m_scalar_type" VALUES(11,11,8);
INSERT INTO "m_scalar_type" VALUES(12,12,2);
INSERT INTO "m_scalar_type" VALUES(13,13,6);
INSERT INTO "m_scalar_type" VALUES(14,14,7);
INSERT INTO "m_scalar_type" VALUES(15,15,2);
INSERT INTO "m_scalar_type" VALUES(18,18,3);
INSERT INTO "m_scalar_type" VALUES(19,19,3);
INSERT INTO "m_scalar_type" VALUES(20,20,8);
INSERT INTO "m_scalar_type" VALUES(21,21,8);
INSERT INTO "m_scalar_type" VALUES(22,22,11);
INSERT INTO "m_scalar_type" VALUES(23,23,6);
INSERT INTO "m_scalar_type" VALUES(24,24,10);
INSERT INTO "m_scalar_type" VALUES(25,25,10);
INSERT INTO "m_scalar_type" VALUES(26,26,13);
INSERT INTO "m_scalar_type" VALUES(27,27,13);
INSERT INTO "m_scalar_type" VALUES(28,28,10);
INSERT INTO "m_scalar_type" VALUES(29,29,14);
INSERT INTO "m_scalar_type" VALUES(30,30,15);
INSERT INTO "m_scalar_type" VALUES(31,31,8);
INSERT INTO "m_scalar_type" VALUES(32,32,8);
INSERT INTO "m_scalar_type" VALUES(33,33,14);
INSERT INTO "m_scalar_type" VALUES(34,34,18);
INSERT INTO "m_scalar_type" VALUES(35,34,11);
INSERT INTO "m_scalar_type" VALUES(36,35,17);
INSERT INTO "m_scalar_type" VALUES(38,36,16);
INSERT INTO "m_scalar_type" VALUES(39,37,19);
INSERT INTO "m_scalar_type" VALUES(40,38,14);
INSERT INTO "m_scalar_type" VALUES(41,39,1);
INSERT INTO "m_scalar_type" VALUES(42,39,20);
INSERT INTO "m_scalar_type" VALUES(43,39,21);
INSERT INTO "m_scalar_type" VALUES(44,40,2);
INSERT INTO "m_scalar_type" VALUES(45,31,1);
INSERT INTO "m_scalar_type" VALUES(46,32,1);
INSERT INTO "m_scalar_type" VALUES(47,41,6);
INSERT INTO "m_scalar_type" VALUES(48,42,6);
INSERT INTO "m_scalar_type" VALUES(49,43,23);
INSERT INTO "m_scalar_type" VALUES(50,44,24);
INSERT INTO "m_scalar_type" VALUES(51,11,1);
INSERT INTO "m_scalar_type" VALUES(52,45,2);
INSERT INTO "m_scalar_type" VALUES(53,46,7);
INSERT INTO "m_scalar_type" VALUES(54,47,6);
INSERT INTO "m_scalar_type" VALUES(55,48,7);
INSERT INTO "m_scalar_type" VALUES(56,49,2);
INSERT INTO "m_scalar_type" VALUES(57,50,6);
INSERT INTO "m_scalar_type" VALUES(58,51,7);
INSERT INTO "m_scalar_type" VALUES(59,52,2);
INSERT INTO "m_scalar_type" VALUES(60,53,2);
INSERT INTO "m_scalar_type" VALUES(61,54,2);
INSERT INTO "m_scalar_type" VALUES(62,55,25);
INSERT INTO "m_scalar_type" VALUES(63,56,26);
INSERT INTO "m_scalar_type" VALUES(64,57,2);
INSERT INTO "m_scalar_type" VALUES(65,58,26);
INSERT INTO "m_scalar_type" VALUES(66,60,7);
INSERT INTO "m_scalar_type" VALUES(67,61,27);
INSERT INTO "m_scalar_type" VALUES(68,62,27);
INSERT INTO "m_scalar_type" VALUES(69,63,27);
INSERT INTO "m_scalar_type" VALUES(70,64,27);
INSERT INTO "m_scalar_type" VALUES(71,65,27);
INSERT INTO "m_scalar_type" VALUES(72,66,27);
INSERT INTO "m_scalar_type" VALUES(73,67,27);

-- 

INSERT INTO "m_type" VALUES(1,1,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "m_type" VALUES(2,1,NULL,2,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "m_type" VALUES(3,1,NULL,3,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "m_type" VALUES(4,1,NULL,4,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "m_type" VALUES(5,1,NULL,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "m_type" VALUES(6,1,NULL,6,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "m_type" VALUES(7,1,NULL,7,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "m_type" VALUES(8,1,NULL,8,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "m_type" VALUES(9,1,NULL,9,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "m_type" VALUES(10,1,NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "m_type" VALUES(11,1,NULL,11,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "m_type" VALUES(12,1,NULL,12,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "m_type" VALUES(13,1,NULL,13,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "m_type" VALUES(14,1,NULL,14,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "m_type" VALUES(15,1,NULL,15,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "m_type" VALUES(18,1,NULL,18,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "m_type" VALUES(19,1,NULL,19,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "m_type" VALUES(20,1,NULL,20,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "m_type" VALUES(21,1,NULL,21,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "m_type" VALUES(22,1,NULL,22,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "m_type" VALUES(23,1,NULL,23,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "m_type" VALUES(24,1,NULL,24,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "m_type" VALUES(25,1,NULL,25,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "m_type" VALUES(26,1,NULL,26,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "m_type" VALUES(27,1,NULL,27,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "m_type" VALUES(28,1,NULL,28,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "m_type" VALUES(29,1,NULL,29,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "m_type" VALUES(30,1,NULL,30,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "m_type" VALUES(31,1,NULL,31,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "m_type" VALUES(32,1,NULL,32,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "m_type" VALUES(33,1,NULL,33,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "m_type" VALUES(34,1,NULL,34,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "m_type" VALUES(35,1,NULL,35,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "m_type" VALUES(36,1,NULL,36,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "m_type" VALUES(38,1,NULL,38,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "m_type" VALUES(39,1,NULL,39,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "m_type" VALUES(40,1,NULL,40,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "m_type" VALUES(41,4,NULL,41,42,43,44,NULL,NULL,NULL,NULL);
INSERT INTO "m_type" VALUES(42,2,NULL,45,46,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "m_type" VALUES(43,1,NULL,47,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "m_type" VALUES(44,1,NULL,48,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "m_type" VALUES(45,1,NULL,49,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "m_type" VALUES(46,1,NULL,50,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "m_type" VALUES(47,1,NULL,51,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "m_type" VALUES(48,1,NULL,52,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "m_type" VALUES(49,1,NULL,53,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "m_type" VALUES(51,1,NULL,54,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "m_type" VALUES(52,1,NULL,55,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "m_type" VALUES(53,1,NULL,56,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "m_type" VALUES(54,1,NULL,57,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "m_type" VALUES(55,1,NULL,58,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "m_type" VALUES(56,1,NULL,59,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "m_type" VALUES(57,1,NULL,61,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "m_type" VALUES(58,1,NULL,62,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "m_type" VALUES(59,1,NULL,63,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "m_type" VALUES(60,1,NULL,64,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "m_type" VALUES(61,1,NULL,65,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "m_type" VALUES(62,1,NULL,66,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "m_type" VALUES(63,1,NULL,67,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "m_type" VALUES(64,1,NULL,68,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "m_type" VALUES(65,1,NULL,69,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "m_type" VALUES(66,1,NULL,70,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "m_type" VALUES(67,1,NULL,71,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "m_type" VALUES(68,1,NULL,72,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "m_type" VALUES(69,1,NULL,73,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "m_type" VALUES(70,1,NULL,60,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

INSERT INTO "m_type_display_order" VALUES(1,5);
INSERT INTO "m_type_display_order" VALUES(2,3);
INSERT INTO "m_type_display_order" VALUES(3,1);
INSERT INTO "m_type_display_order" VALUES(4,2);
INSERT INTO "m_type_display_order" VALUES(5,4);
INSERT INTO "m_type_display_order" VALUES(6,22);
INSERT INTO "m_type_display_order" VALUES(7,39);
INSERT INTO "m_type_display_order" VALUES(8,30);
INSERT INTO "m_type_display_order" VALUES(9,29);
INSERT INTO "m_type_display_order" VALUES(10,33);
INSERT INTO "m_type_display_order" VALUES(11,40);
INSERT INTO "m_type_display_order" VALUES(12,23);
INSERT INTO "m_type_display_order" VALUES(13,8);
INSERT INTO "m_type_display_order" VALUES(14,13);
INSERT INTO "m_type_display_order" VALUES(15,14);
INSERT INTO "m_type_display_order" VALUES(16,52);
INSERT INTO "m_type_display_order" VALUES(17,18);
INSERT INTO "m_type_display_order" VALUES(18,20);
INSERT INTO "m_type_display_order" VALUES(19,21);
INSERT INTO "m_type_display_order" VALUES(20,11);
INSERT INTO "m_type_display_order" VALUES(21,12);
INSERT INTO "m_type_display_order" VALUES(22,31);
INSERT INTO "m_type_display_order" VALUES(23,32);
INSERT INTO "m_type_display_order" VALUES(24,19);
INSERT INTO "m_type_display_order" VALUES(25,6);
INSERT INTO "m_type_display_order" VALUES(26,7);
INSERT INTO "m_type_display_order" VALUES(27,25);
INSERT INTO "m_type_display_order" VALUES(28,24);
INSERT INTO "m_type_display_order" VALUES(29,9);
INSERT INTO "m_type_display_order" VALUES(30,28);
INSERT INTO "m_type_display_order" VALUES(31,27);
INSERT INTO "m_type_display_order" VALUES(32,26);
INSERT INTO "m_type_display_order" VALUES(33,10);
INSERT INTO "m_type_display_order" VALUES(34,34);
INSERT INTO "m_type_display_order" VALUES(35,35);
INSERT INTO "m_type_display_order" VALUES(36,36);
INSERT INTO "m_type_display_order" VALUES(37,38);
INSERT INTO "m_type_display_order" VALUES(38,47);
INSERT INTO "m_type_display_order" VALUES(39,48);
INSERT INTO "m_type_display_order" VALUES(40,49);
INSERT INTO "m_type_display_order" VALUES(41,50);
