#!/bin/bash

if [ ! -f /tmp/lock_populate_xenia_nws ]; then
  touch /tmp/lock_populate_xenia_nws

  startTime=`date -u`
  echo "Start time: $startTime\n" > /home/xeniaprod/tmp/log/scout_nws.log 2>&1
  
  /home/xeniaprod/scripts/postgresql/feeds/federal/mk_sql_for_xenia.pl nws 24 /home/xeniaprod/tmp/sqlfiles/nws.sql debug >> /home/xeniaprod/tmp/log/scout_nws.log 2>&1
  psql -U xeniaprod -d xenia -f /home/xeniaprod/tmp/sqlfiles/nws.sql >> /home/xeniaprod/tmp/log/scout_nws.log 2>&1
  rm -f /tmp/lock_populate_xenia_nws

  startTime=`date -u`
  echo "\nEnd time: $startTime" >> /home/xeniaprod/tmp/log/scout_nws.log 2>&1
  
else
  startTime=`date -u`
  echo "Lock file exists, cannot run script: $startTime\n" >> /home/xeniaprod/tmp/log/scout_nws.log 2>&1  
fi